-- This contains the model of the fox river sports website.
--
-- Author: Josh Toepfer 8/22/2014
-- Revisions
-- 10/02/2014   Added more entities to the list
------------------------------------------------------------
CREATE TABLE FOXRIVERSPORTS.CAMPUS (
  CAMPUSID  INT          NOT NULL GENERATED ALWAYS AS IDENTITY,
  NAME      VARCHAR(200) NOT NULL,
CONSTRAINT CAMPUS_PK PRIMARY KEY (CAMPUSID)
);

-- The system contains an over all sports table that contains sport that are supported.
CREATE TABLE FOXRIVERSPORTS.SPORTS (
  SPORTID     INT           NOT NULL GENERATED ALWAYS AS IDENTITY,
  CODE        VARCHAR(15)   NOT NULL,
  NAME        VARCHAR(150)  NOT NULL,
  STARTDATE   DATE          NOT NULL,
  ENDDATE     DATE         ,
CONSTRAINT SPORTS_PK PRIMARY KEY (SPORTID) 
);

-- this contains more details about the sport.
CREATE TABLE FOXRIVERSPORTS.SPORTSDETAIL (
  SPORTID   INT       NOT NULL GENERATED ALWAYS AS IDENTITY,
  DESCRIPTION VARCHAR(4000),
CONSTRAINT SPORTSDETAIL_PK PRIMARY KEY (SPORTID),
CONSTRAINT SPORTSDETAIL_FK FOREIGN KEY (SPORTID) REFERENCES FOXRIVERSPORTS.SPORTS (SPORTID)
);

CREATE TABLE FOXRIVERSPORTS.LEAGUES (
  LEAGUEID    INT          NOT NULL GENERATED ALWAYS AS IDENTITY,
  LEAGUECODE  VARCHAR(20)  NOT NULL,
  SPORTID     INT          NOT NULL,
  NAME        VARCHAR(500) NOT NULL,
  DESCRIPTION VARCHAR(1000),
CONSTRAINT SPORTSLEAGUE_PK PRIMARY KEY (LEAGUEID),
CONSTRAINT SPORTSLEAGUE_FK FOREIGN KEY (SPORTID) REFERENCES FOXRIVERSPORTS.SPORTS (SPORTID)
);

-- sport specific rules
CREATE TABLE FOXRIVERSPORTS.RULES (
  RULEID       INT           NOT NULL GENERATED ALWAYS AS IDENTITY,
  RULENO       VARCHAR(10)   NOT NULL,
  SPORTID      INT           NOT NULL,
  LEAGUEID     INT,
  PARENTRULEID INT,
  DESCRIPTION  VARCHAR(500),
  CREATEDATETIME DATE        NOT NULL,
  UPDATEDATETIME DATE        NOT NULL,
CONSTRAINT RULE_PK PRIMARY KEY (RULEID),
CONSTRAINT SPORTSRULE_FK FOREIGN KEY (SPORTID) REFERENCES FOXRIVERSPORTS.SPORTS (SPORTID),
CONSTRAINT LEAGUERULE_FK FOREIGN KEY (LEAGUEID) REFERENCES FOXRIVERSPORTS.LEAGUES (LEAGUEID)
);

CREATE TABLE FOXRIVERSPORTS.SECTIONS (
  SECTIONID   INT           NOT NULL GENERATED ALWAYS AS IDENTITY,
  SECTIONNO   VARCHAR(10)   NOT NULL,
  RULEID      INT           NOT NULL,
  DESCRIPTION VARCHAR(500),
  CREATEDATETIME DATE       NOT NULL,
  UPDATEDATETIME DATE       NOT NULL,
CONSTRAINT SECTION_PK PRIMARY KEY (SECTIONID),
CONSTRAINT SECTIONRULE_FK FOREIGN KEY (RULEID) REFERENCES FOXRIVERSPORTS.RULES (RULEID)
);

CREATE TABLE FOXRIVERSPORTS.ARTICLES (
  ARTICLEID       INT          NOT NULL GENERATED ALWAYS AS IDENTITY,
  ARTICLENO       VARCHAR(10)  NOT NULL,
  SECTIONID       INT          NOT NULL,
  PARENTARTICLEID INT,
  DESCRIPTION     VARCHAR(500),
  CREATEDATETIME  DATE          NOT NULL,
  UPDATEDATETIME  DATE          NOT NULL,
CONSTRAINT ARTICLE_PK PRIMARY KEY (ARTICLEID),
CONSTRAINT ARTICLESECTION_FK FOREIGN KEY (SECTIONID) REFERENCES FOXRIVERSPORTS.SECTIONS (SECTIONID),
CONSTRAINT PARENTARTICLE_FK FOREIGN KEY (PARENTARTICLEID) REFERENCES FOXRIVERSPORTS.ARTICLES (ARTICLEID)
);

CREATE TABLE FOXRIVERSPORTS.PEOPLE (
  PERSONID  INT NOT NULL GENERATED ALWAYS AS IDENTITY,
  FIRSTNAME VARCHAR(150),
  LASTNAME  VARCHAR(150),
  BIRTHDATE DATE,
CONSTRAINT PEOPLE_PK PRIMARY KEY (PERSONID)
);

CREATE TABLE FOXRIVERSPORTS.SEASONS (
  SEASONID  INT NOT NULL GENERATED ALWAYS AS IDENTITY,
  LEAGUEID  INT NOT NULL,
  STARTDATE DATE NOT NULL,
  ENDDATE   DATE,
  NAME      VARCHAR(256),
  FREQUENCY VARCHAR(50),
  TRADEDEADLINE DATE NOT NULL,
CONSTRAINT SEASONS_PK PRIMARY KEY (SEASONID),
CONSTRAINT LEAGUESEASON_FK FOREIGN KEY (LEAGUEID) REFERENCES FOXRIVERSPORTS.LEAGUES (LEAGUEID)
);

CREATE TABLE FOXRIVERSPORTS.TEAMS (
  TEAMID   INT NOT NULL GENERATED ALWAYS AS IDENTITY,
  SEASONID INT NOT NULL,
  NAME     VARCHAR(256),
CONSTRAINT TEAM_PK PRIMARY KEY (TEAMID),
CONSTRAINT SEASONTEAM_FK FOREIGN KEY (SEASONID) REFERENCES FOXRIVERSPORTS.SEASONS (SEASONID)
);

CREATE TABLE FOXRIVERSPORTS.GAMES (
  GAMEID     INT NOT NULL GENERATED ALWAYS AS IDENTITY,
  SEASONID   INT NOT NULL,
  DATETIME   DATE NOT NULL,
  HOMEID     INT NOT NULL,
  VISITORID  INT NOT NULL,
CONSTRAINT GAME_PK PRIMARY KEY (GAMEID),
CONSTRAINT SEASONGAME_FK FOREIGN KEY (SEASONID) REFERENCES FOXRIVERSPORTS.SEASONS (SEASONID),
CONSTRAINT HOMETEAM_FK FOREIGN KEY (HOMEID) REFERENCES FOXRIVERSPORTS.TEAMS (TEAMID),
CONSTRAINT VISITORTEAM_FK FOREIGN KEY (VISITORID) REFERENCES FOXRIVERSPORTS.TEAMS (TEAMID)
);

CREATE TABLE FOXRIVERSPORTS.OFFICIALS (
  PERSONID INT  NOT NULL,
  GAMEID   INT  NOT NULL,
  PRIMARYIND CHAR(1) NOT NULL,
CONSTRAINT OFFICIALS_PK PRIMARY KEY(PERSONID, GAMEID),
CONSTRAINT OFFICALPERSON_FK FOREIGN KEY (PERSONID) REFERENCES FOXRIVERSPORTS.PEOPLE (PERSONID),
CONSTRAINT OFFICALGAME_FK FOREIGN KEY (GAMEID) REFERENCES FOXRIVERSPORTS.GAMES (GAMEID)
);

CREATE TABLE FOXRIVERSPORTS.CAPTAINS (
  TEAMID INT NOT NULL,
  PERSONID INT NOT NULL,
  PRIMARYIND CHAR(1) NOT NULL,
CONSTRAINT CAPTAINS_PK PRIMARY KEY(TEAMID, PERSONID),
CONSTRAINT PERSONCAPTAIN_FK FOREIGN KEY (PERSONID) REFERENCES FOXRIVERSPORTS.PEOPLE (PERSONID),
CONSTRAINT TEAMCAPTAIN_FK FOREIGN KEY (TEAMID) REFERENCES FOXRIVERSPORTS.TEAMS (TEAMID)
);

CREATE TABLE FOXRIVERSPORTS.ADDRESSES (
  ADDRESSID  INT NOT NULL GENERATED ALWAYS AS IDENTITY,
  OBJECTTYPE VARCHAR(50) NOT NULL,
  OBJECTID   INT NOT NULL,
  ADDRESSONE VARCHAR(256),
  ADDRESSTWO VARCHAR(256),
  CITY       VARCHAR(120),
  STATE      CHAR(2),
  POSTALCODE VARCHAR(9),
CONSTRAINT ADDRESSES_PK PRIMARY KEY (ADDRESSID)
);

CREATE TABLE FOXRIVERSPORTS.NOTIFICATIONS (
  NOTIFICATIONID INT NOT NULL GENERATED ALWAYS AS IDENTITY,
  SPORTID        INT NOT NULL,
  PERSONID       INT NOT NULL,
CONSTRAINT NOTIFICATION_PK PRIMARY KEY (NOTIFICATIONID),
CONSTRAINT SPORTSNOTIFICATION_FK FOREIGN KEY (SPORTID) REFERENCES FOXRIVERSPORTS.SPORTS (SPORTID),
CONSTRAINT NOTIFICATIONPERSON_FK FOREIGN KEY (PERSONID) REFERENCES FOXRIVERSPORTS.PEOPLE (PERSONID)
);

