-- This file contains all the drop scripts to drop the entire database so that it
--  can be rebuilt from scratch using the model script.
--
-- Author: Josh Toepfer 8/22/2014
-- Revisions
-- 10/02/2014   Updated the script to work by removing tables in proper order.
------------------------------------------------------------
DROP TABLE FOXRIVERSPORTS.NOTIFICATIONS;
DROP TABLE FOXRIVERSPORTS.ARTICLES;
DROP TABLE FOXRIVERSPORTS.SECTIONS;
DROP TABLE FOXRIVERSPORTS.RULES;
DROP TABLE FOXRIVERSPORTS.OFFICIALS;
DROP TABLE FOXRIVERSPORTS.GAMES;
DROP TABLE FOXRIVERSPORTS.CAPTAINS;
DROP TABLE FOXRIVERSPORTS.TEAMS;
DROP TABLE FOXRIVERSPORTS.SEASONS;
DROP TABLE FOXRIVERSPORTS.LEAGUES;
DROP TABLE FOXRIVERSPORTS.SPORTSDETAIL;
DROP TABLE FOXRIVERSPORTS.SPORTS;
DROP TABLE FOXRIVERSPORTS.CAMPUS;
DROP TABLE FOXRIVERSPORTS.PEOPLE;
DROP TABLE FOXRIVERSPORTS.ADDRESSES;
