language: java
script: mvn clean package -DskipTests=true
jdk:
- oraclejdk7
deploy:
  provider: openshift
  user: joshua.toepfer@gmail.com
  password:
    secure: ngIHWkY6Q2G6QV/cYcj+9YzyfKdJKFgqaPb2e1cSikkafo49Ym+vWBm/dreWKjhwohgmtrtTZ9InjZgrdDN08LH66W6pzgAbEHdbFUcSEpNosrGehalagBkrvt4mEG4CutivmPRjPQdtgNWb0RzhhucjCHeb0jXBrj9cMwgquPrHbSxCXKNdzdCLkQ2t3JBPu2r8cWGTWmgsa4loyw39H16HVbXRamj8675hZd5IoQW+LOFqfsTgvOkwWURa8gWuAsqnw1vqBM8QtENMI6z0BnmD34fwNoDmtKOvDLd7pBn/VoXL51UzgIHvF6gYdAQk28ad9a9p7pDN5FlGhVHbHC3Tu0jbrCvdmXCsj1vXMTX42Jgvh3qNzzKp3mLdD+jCcXuQsPu2U1dmuKJy5x6vm9ojMVHNKPSjzGmvGh6nP4gHME7X8ekN9vVpWDH4Fw88FFHmuAdYCxltf8DvjodAmtu07DJ9dgp31DaktyR24eg5b7a+jViIQsRl0TtOZ66UUlgXyVYCC1zD2uiLZnPDB/re4kfKgxPBL/mw4ZaQ8+kEiZvSqlc1EBVn1yQxSNCfwB8wk6eLEIw0/Sh3YHCvTwigZZyeuFdV/WYdACQmNlTH6hvrySZfGU3TEUYXjOu5skqkDMBDmprfeDLhDpZcyZrx441NzDnf0MihdtNOuAc=
  app: foxriversports
  domain: foxriversports
  on:
    repo: jtoepfer/foxriversports
